apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.NAMESPACE }}
spec:
  clusterIP: {{ .Values.SERVICE.TYPE }}
  selector:
    app: postgresql
  ports:
    - port: {{ .Values.SERVICE.PORT }}