apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{ .Values.NAMESPACE }}
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.IMAGE.REPOSITORY }}:{{ .Values.IMAGE.TAG }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: POSTGRES_DB
              value: ragdb
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
          ports:
            - containerPort: {{ .Values.SERVICE.PORT }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U ragdb"
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi