--liquibase formatted sql
--changeset vibo:003-create-rag-tables

CREATE TABLE IF NOT EXISTS loaded_document
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name     VARCHAR(255) NOT NULL,
    content_hash  VARCHAR(64)  NOT NULL,
    document_type VARCHAR(10)  NOT NULL,
    chunk_count   INTEGER,
    loaded_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_document UNIQUE (file_name, content_hash)
);

CREATE TABLE IF NOT EXISTS vector_store
(
    id        VARCHAR(255) PRIMARY KEY,
    content   TEXT,
    metadata  JSON,
    embedding VECTOR(1024)
);
