apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama-service
  name: ollama-service
  namespace: {{ .Values.NAMESPACE }}
spec:
  ports:
    - port: {{ .Values.SERVICE.PORT }}
      protocol: TCP
      targetPort: {{ .Values.SERVICE.PORT }}
  selector:
    app: ollama-service
  type: {{ .Values.SERVICE.TYPE }}
status:
  loadBalancer: {}