apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llm-host-service
  name: llm-host-service
spec:
  replicas: {{ .Values.REPLICA_COUNT }}
  selector:
    matchLabels:
      app: llm-host-service
  strategy: {}
  template:
    metadata:
      labels:
        app: llm-host-service
    spec:
      containers:
        - image: {{ .Values.IMAGE.REPOSITORY }}:{{ .Values.IMAGE.TAG }}
          name: host
          env:
            - name: DB_HOST
              value: postgresql-0.postgresql.postgres.svc.cluster.local
            - name: OLLAMA_HOST
              value: ollama-service.ollama.svc.cluster.local
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.SERVICE.PORT }}
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.SERVICE.PORT }}
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
          resources: {}
status: {}