apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SECRET_NAME }}
type: Opaque
data:
  username: {{ .Values.AUTH.USERNAME | b64enc | quote }}
  password: {{ .Values.AUTH.PASSWORD | b64enc | quote }}
